services:
  server:
    build: ./backend
    restart: unless-stopped
    volumes:
      - ./backend:/usr/app
    ports:
      - 3000:3000
    tty: true
    working_dir: /usr/app
    command: sh -c "npm install && npm run dev" 
  client:
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/app
    ports:
      - 9000:9000
    tty: true
    working_dir: /usr/app
    command: sh -c "yarn install && quasar dev"
networks:
  proxy:
    name: hackathon-caixa
